# Use the official Python image from the Docker Hub
FROM python:3.12-slim

# Set the working directory
WORKDIR /Flask

# Install system dependencies and pip
RUN apt-get update && apt-get install -y \
    build-essential \
    libmariadb-dev-compat \
    libmariadb-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the image
COPY requirements.txt /Flask/

# Install the dependencies
RUN pip install --no-cache-dir -r /Flask/requirements.txt

# Copy the Flask app contents into the image
COPY Flask /Flask/Flask

# Verify Flask installation
RUN python -m flask --version

# Debugging: List the contents of the /Flask directory
RUN ls -l /Flask

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run the Flask application directly
CMD ["python", "/Flask/app.py"]
